chore(license): use same version of dd-rust-license-tool

diff --git a/.github/workflows/lint.yml b/.github/workflows/lint.yml
--- a/.github/workflows/lint.yml
+++ b/.github/workflows/lint.yml
@@ -81,16 +81,38 @@ jobs:
     steps:
       - name: Checkout sources
         uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # 4.2.2
+      # Keep version in sync with: scripts/update_license_3rdparty.sh (TOOL_VERSION) and scripts/Dockerfile.license (ARG TOOL_VERSION)
       - name: Cache dd-rust-license-tool
         uses: actions/cache@d4323d4df104b026a6aa633fdb11d772146be0bf # 4.2.2
         with:
           path: |
+            ~/.cargo/registry/
+            ~/.cargo/git/db/
             ~/.cargo/bin/dd-rust-license-tool
             ~/.cargo/.crates.toml
             ~/.cargo/.crates2.json
-          key: dd-rust-license-tool-1.0.6
-      - run: cargo install dd-rust-license-tool --version "1.0.6" --locked
-      - run: dd-rust-license-tool check
+          key: dd-rust-license-tool-1.0.6-v2
+      - run: cargo install --list | grep -qF "dd-rust-license-tool v1.0.6" || cargo install dd-rust-license-tool --version "1.0.6" --locked
+      - name: Generate new LICENSE-3rdparty.csv and check against the previous
+        run: |
+          if ! dd-rust-license-tool dump > /tmp/CI.csv 2> /tmp/CI.error; then
+            echo "ERROR: dd-rust-license-tool dump failed! See error output below:"
+            cat /tmp/CI.error
+            exit 1
+          fi
+          if ! diff /tmp/CI.csv LICENSE-3rdparty.csv; then
+            echo "Differences detected in LICENSE-3rdparty.csv."
+            echo "Please run './scripts/update_license_3rdparty.sh' to update the file and commit the changes."
+            exit 1
+          fi
+          echo "No differences found."
+      - name: Export generated license file on failure
+        if: failure()
+        uses: actions/upload-artifact@4cec3d8aa04e39d1a68397de0c4cd6fb9dce8ec1 # v4.6.1
+        with:
+          name: LICENSE-3rdparty.csv
+          path: /tmp/CI.csv
+          overwrite: true
 
   codeowners-validator:
     runs-on: ubuntu-latest
